version: 2.1

jobs:
  test-python:
    parameters:
      python-version:
        type: string
        default: "3.9"
    docker:
      - image: cimg/python:<< parameters.python-version >>
    resource_class: xlarge # 8 core machines to get the hypothesis tests to run in a reasonable time
    steps:
      - checkout
      - run:
          name: Install uv
          command: |
            python -m pip install uv
      - run:
          name: Install Python dependencies
          command: |
            uv sync --all-extras
      - run:
          name: Build and run tests
          command: |
            uv build
            export TOX_PYTHON=py$(echo "<< parameters.python-version >>" | tr -d .)
            uv run python -Im tox run --installpkg "dist/*.whl" -e ${TOX_PYTHON}-pydantic<< parameters.pydantic >>-tests
          environment:
            HYPOTHESIS_PROFILE: ci

workflows:
  test-python-multiple-versions:
    jobs:
      # Run the job with the default Python version first
      - test-python:
          name: "test-python-v<< matrix.python-version >>-pydantic-v<< matrix.pydantic >>"
          filters:
            branches:
              ignore: "main"
          matrix:
            parameters:
              python-version: ["3.9"]
              pydantic: ["1", "2"]
      - test-python:
          name: "test-python-v<< matrix.python-version >>-pydantic-v<< matrix.pydantic >>"
          filters:
            branches:
              ignore: "main"
          matrix:
            parameters:
              python-version: ["3.10", "3.11", "3.12", "3.13"] # 3.9 has already been tested
              pydantic: ["1", "2"]
          requires:
            - test-python-v3.9-pydantic-v1
            - test-python-v3.9-pydantic-v2
