version: 2.1

jobs:
  test-python:
    parameters:
      python-version:
        type: string
        default: "3.8"
    docker:
      - image: cimg/python:<< parameters.python-version >>
    resource_class: xlarge # 8 core machines to get the hypothesis tests to run in a reasonable time
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: |
            python -m pip install '.[dev]'
            yes | python -m mypy --install-types replicate || true
      - run:
          name: Run tests
          command: make test-python
          environment:
            HYPOTHESIS_PROFILE: ci
  typecheck-python:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: |
            python -m pip install '.[dev]'
            yes | python -m mypy --install-types replicate || true
      - run:
          name: Run typechecking
          command: make lint-python

workflows:
  test-python-multiple-versions:
    jobs:
      # Run the job with the default Python version first
      - test-python:
          name: test-default-python
          filters:
            branches:
              ignore: "main"
      - test-python:
          name: test-multiple-python-versions
          filters:
            branches:
              ignore: "main"
          matrix:
            parameters:
              python-version: ["3.9", "3.10", "3.11", "3.12"] # 3.8 has already been tested
          requires:
            - test-default-python
      - typecheck-python:
          name: typecheck-python
          filters:
            branches:
              ignore: "main"
