name: Cardinal Blue - CI

on:
  push:
    branches:
      - cb-main
    tags:
      - "**"
  pull_request:
    branches:
      - cb-main
  merge_group:
    branches:
      - cb-main
    types:
      - checks_requested
jobs:
  test-python:
    name: "Test Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install '.[dev]'
      - name: Test
        run: make test-python
        env:
          HYPOTHESIS_PROFILE: ci

  typecheck-python:
    name: "Typecheck and lint Python"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Python dependencies
        run: |
          python -m pip install '.[dev]'
      - name: Run typechecking
        run: |
          make lint-python
