name: Python Test

on:
  push:
    branches:
      - remove_unused_features
    tags:
      - "**"
  pull_request:
    branches:
      - remove_unused_features
  merge_group:
    branches:
      - remove_unused_features
    types:
      - checks_requested
jobs:
  test-python:
    name: "Test Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest-8-cores
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install '.[dev]'
          yes | python -m mypy --install-types replicate || true
      - name: Test
        run: make test-python
        env:
          HYPOTHESIS_PROFILE: ci
